SELECT JOB_ID, COUNT(JOB_ID) FROM employees
GROUP BY JOB_ID;

SELECT MIN(SALARY), MANAGER_ID FROM employees;

SELECT SUM(SALARY), DEPARTMENT_ID FROM employees
GROUP BY DEPARTMENT_ID;

SELECT employees.JOB_ID, AVG(SALARY) FROM employees
JOIN jobs
ON jobs.JOB_ID = employees.JOB_ID
WHERE JOB_TITLE NOT LIKE 'Programmer'
GROUP BY employees.JOB_ID;

SELECT employees.JOB_ID, MAX_SALARY FROM employees
JOIN jobs
ON jobs.JOB_ID = employees.JOB_ID
HAVING MAX_SALARY > 4000;

SELECT AVG(SALARY), DEPARTMENT_ID FROM employees
GROUP BY DEPARTMENT_ID
HAVING COUNT(DEPARTMENT_ID) > 10;