SELECT DISTINCT(DEPARTMENT_ID) FROM employees;

SELECT * FROM employees
ORDER BY FIRST_NAME DESC;

SELECT SUM(SALARY) FROM employees;

SELECT MIN(SALARY) FROM employees;

SELECT MAX(SALARY) FROM employees;

SELECT AVG(SALARY) FROM employees;

SELECT COUNT(EMPLOYEE_ID) FROM employees;

SELECT COUNT(JOB_ID) FROM jobs;

SELECT UPPER(FIRST_NAME) FROM employees;

SELECT SUBSTRING(FIRST_NAME, 1, 3) FROM employees;

SELECT CONCAT(FIRST_NAME, " " , LAST_NAME) FROM employees;

SELECT TRIM(FIRST_NAME) FROM employees;

SELECT LENGTH(FIRST_NAME) FROM employees;

SELECT LENGTH(LAST_NAME) FROM employees;

SELECT * FROM employees LIMIT 10;