SELECT LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_ID FROM locations
NATURAL JOIN departments;

SELECT FIRST_NAME, LAST_NAME, employees.DEPARTMENT_ID, DEPARTMENT_NAME FROM employees
JOIN departments
ON departments.DEPARTMENT_ID = employees.DEPARTMENT_ID;

SELECT DISTINCT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, DEPARTMENT_ID, DEPARTMENT_NAME, CITY FROM employees
NATURAL JOIN departments, locations, jobs
WHERE CITY = 'London';

SELECT COUNT(EMPLOYEE_ID) AS EMPLOYEE_NUMBER, DEPARTMENT_NAME FROM employees
JOIN departments
ON departments.DEPARTMENT_ID = employees.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees
WHERE HIRE_DATE > (SELECT HIRE_DATE FROM employees WHERE LAST_NAME = 'Jones')