SELECT FIRST_NAME, LAST_NAME, SALARY FROM employees
WHERE SALARY > (SELECT SALARY FROM employees WHERE LAST_NAME = 'BULL');

SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM departments WHERE DEPARTMENT_NAME LIKE 'IT')

SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE JOB_ID IN (SELECT JOB_ID FROM jobs WHERE JOB_TITLE LIKE '%manager%');

SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE SALARY > (SELECT AVG(SALARY) FROM employees);

SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE SALARY = (SELECT MIN_SALARY FROM jobs WHERE employees.JOB_ID = jobs.JOB_ID);

SELECT FIRST_NAME, LAST_NAME FROM employees
WHERE SALARY = (SELECT MIN(SALARY) FROM jobs);

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, (SELECT DEPARTMENT_NAME FROM departments WHERE departments.DEPARTMENT_ID = employees.DEPARTMENT_ID) AS DEPARTMENT_NAME FROM employees;

SELECT * FROM (SELECT * FROM employees ORDER BY EMPLOYEE_ID DESC LIMIT 10) AS LAST_TEN_RECORDS ORDER BY EMPLOYEE_ID ASC